#!/bin/bash

# Sloppy chroot automation

if [[ $(mount | grep /mnt) ]]; then
	echo -e "WARNING: Something is already on /mnt.\nContinue using /mnt? y/n"
	read cont
	case $cont in
	y)
		echo "Using whatever is mounted on /mnt..."
		;;
	*)
		exit 0
		;;
	esac
elif [[ ! $1 ]]; then
	echo "Nothing is on /mnt, so you need to specify a device"
	exit 0
else
	echo "Sloppily mounting $1 to /mnt.  Someone should really write a better script."
	mount "$1" /mnt
fi
echo "binding pric, sys, dev, and dev/pts to /mnt..."
mount -o bind /proc /mnt/proc
mount -o bind /sys /mnt/sys
mount -o bind /dev /mnt/dev
mount -o bind /dev/pts /mnt/dev/pts
echo "Entering chroot with /bin/bash...enjoy!"
chroot /mnt /bin/sh
