#!/bin/ksh

# A more perfect iridium container
# I had some issues with using folders in /tmp, so 
# I decided to make a better way.

# Define a temporary directory
tmpdir="~/.irid-tmp";
# Remove the existing folder, just in case
rm -r -P $tmpdir 2> /dev/null;
mkdir $tmpdir && \
iridium --incognito --user-data-dir=$tmpdir;
rm -r -P $tmpdir
