#!/bin/ksh

# Notes for managing jobs
# In the form of a script

# https://unix.stackexchange.com/questions/2107/how-to-suspend-and-resume-processes
# Debugging
#echo $1
#echo $2

case $1 in 
	pause)
		kill -TSTP $2
		;;
	resume)
		kill -CONT $2
		;;
	*)
		echo "Usage: jerbs [pause | resume] [pid]"
		;;
esac

